import {
  Company,
  User,
  Client,
  Quote,
  Appointment,
  Project,
  FinancialEntry,
  FinancialExpense,
  AppNotification,
  MonthlyGoal
} from '../types';

export const DEFAULT_COMPANY_ID = 'comp_ozi_01';

export const INITIAL_COMPANY: Company = {
  id: DEFAULT_COMPANY_ID,
  trade_name: 'Nexvoltora Gestão e Prestação de Serviços',
  legal_name: 'Nexvoltora Gestão e Prestação de Serviços Ltda',
  cnpj: '45.892.123/0001-90',
  cpf: '',
  phone: '(11) 3456-7890',
  whatsapp: '(11) 98765-4321',
  email: 'contato@nexvoltora.com.br',
  website: 'https://nexvoltora.com.br',
  instagram: '@nexvoltora',
  address: 'Av. Paulista',
  number: '1842',
  complement: 'Conjunto 142 - 14º andar',
  neighborhood: 'Bela Vista',
  city: 'São Paulo',
  state: 'SP',
  zip_code: '01310-200',
  logo_url: '/nexvoltora.png',
};

const _nowMs = Date.now();
const _dayMs = 24 * 60 * 60 * 1000;

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_master_impacto',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Administrador Master',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    role: 'ADMINISTRADOR',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'vendas.impactodigital2@gmail.com',
    password: 'password',
    active: true,
    created_at: '2025-01-01',
    subscriptionStatus: 'active',
    subscription_status: 'active',
    trial_start: new Date(_nowMs - 30 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 365 * _dayMs).toISOString(),
    trialEndsAt: new Date(_nowMs + 365 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_fabio',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Fábio Mendes',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    role: 'ADMINISTRADOR',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'fabio@oziservicos.com.br',
    active: true,
    created_at: '2025-01-10',
    subscriptionStatus: 'active',
    subscription_status: 'active',
    trial_start: new Date(_nowMs - 30 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 30 * _dayMs).toISOString(),
    trialEndsAt: new Date(_nowMs + 30 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_marcos',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Marcos Rezende (Eletrotécnica Rezende)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    role: 'GERENTE',
    phone: '(11) 97654-3210',
    whatsapp: '(11) 97654-3210',
    email: 'marcos@oziservicos.com.br',
    active: true,
    created_at: '2025-01-15',
    subscriptionStatus: 'trial',
    subscription_status: 'trial',
    trial_start: new Date(_nowMs - 14 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 1 * _dayMs).toISOString(), // 1 dia restante -> 🚨 Expira hoje / amanhã
    trialEndsAt: new Date(_nowMs + 1 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_larissa',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Larissa Alencar (Alencar Pinturas)',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    role: 'ORÇAMENTISTA',
    phone: '(11) 96543-2109',
    whatsapp: '(11) 96543-2109',
    email: 'larissa@oziservicos.com.br',
    active: true,
    created_at: '2025-02-01',
    subscriptionStatus: 'trial',
    subscription_status: 'trial',
    trial_start: new Date(_nowMs - 12 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 3 * _dayMs).toISOString(), // 3 dias restantes -> ⚠️ Restam 3 dias
    trialEndsAt: new Date(_nowMs + 3 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_joao',
    company_id: DEFAULT_COMPANY_ID,
    name: 'João Pedro Mestre (Mestre Reformas)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    role: 'FUNCIONÁRIO',
    phone: '(11) 95432-1098',
    whatsapp: '(11) 95432-1098',
    email: 'joao.obras@oziservicos.com.br',
    active: true,
    created_at: '2025-02-05',
    subscriptionStatus: 'trial',
    subscription_status: 'trial',
    trial_start: new Date(_nowMs - 10 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 5 * _dayMs).toISOString(), // 5 dias restantes -> ⚠️ Restam 5 dias
    trialEndsAt: new Date(_nowMs + 5 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_rodrigo',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Rodrigo Silva (R.S Climatização)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    role: 'ADMINISTRADOR',
    phone: '(11) 94321-8765',
    whatsapp: '(11) 94321-8765',
    email: 'rodrigo.clima@gmail.com',
    active: true,
    created_at: '2025-02-10',
    subscriptionStatus: 'expired',
    subscription_status: 'expired',
    trial_start: new Date(_nowMs - 20 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs - 2 * _dayMs).toISOString(), // Já venceu -> 🚨 Expirado
    trialEndsAt: new Date(_nowMs - 2 * _dayMs).toISOString().split('T')[0],
  },
  {
    id: 'usr_carolina',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Carolina Mendes (Mendes Construções)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    role: 'ADMINISTRADOR',
    phone: '(11) 93210-9876',
    whatsapp: '(11) 93210-9876',
    email: 'carolina.mendes@mendescon.com.br',
    active: true,
    created_at: '2025-02-15',
    subscriptionStatus: 'trial',
    subscription_status: 'trial',
    trial_start: new Date(_nowMs - 1 * _dayMs).toISOString(),
    trial_end: new Date(_nowMs + 14 * _dayMs).toISOString(), // 14 dias restantes
    trialEndsAt: new Date(_nowMs + 14 * _dayMs).toISOString().split('T')[0],
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_carlos',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Carlos Silva',
    document: '284.918.472-10',
    phone: '(11) 99123-4567',
    whatsapp: '(11) 99123-4567',
    email: 'carlos.silva@gmail.com',
    address: 'Rua das Palmeiras',
    number: '350',
    complement: 'Apto 82',
    neighborhood: 'Moema',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '04512-001',
    notes: 'Reforma de apartamento completo (sala + quartos). Cliente prefere contato à tarde.',
    created_at: '2025-02-10',
  },
  {
    id: 'cli_maria',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Maria Santos Oliveira',
    document: '194.829.381-04',
    phone: '(11) 98234-5678',
    whatsapp: '(11) 98234-5678',
    email: 'maria.santos@outlook.com',
    address: 'Alameda dos Anapurus',
    number: '1240',
    complement: 'Casa',
    neighborhood: 'Indianópolis',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '04087-003',
    notes: 'Pintura externa, impermeabilização de fachada e revisão de calhas.',
    created_at: '2025-02-14',
  },
  {
    id: 'cli_empresa_abc',
    company_id: DEFAULT_COMPANY_ID,
    name: 'Empresa ABC Empreendimentos',
    document: '12.345.678/0001-99',
    phone: '(11) 3210-9876',
    whatsapp: '(11) 97345-6789',
    email: 'engenharia@empresaabc.com.br',
    address: 'Av. Brigadeiro Faria Lima',
    number: '3477',
    complement: '9º Andar',
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '04538-133',
    notes: 'Adequação elétrica e iluminação corporativa em 2 andares.',
    created_at: '2025-01-20',
  },
  {
    id: 'cli_joao_silva',
    company_id: DEFAULT_COMPANY_ID,
    name: 'João Silva Souza',
    document: '333.444.555-66',
    phone: '(11) 96456-7890',
    whatsapp: '(11) 96456-7890',
    email: 'joaosilva.arq@uol.com.br',
    address: 'Rua Bela Cintra',
    number: '740',
    complement: '',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '01415-000',
    notes: 'Construção de mezanino metálico e piso vinílico comercial.',
    created_at: '2025-02-18',
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'orc_001',
    code: 'ORC-2025-001',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    client_phone: '(11) 99123-4567',
    client_address: 'Rua das Palmeiras, 350 - Moema, São Paulo - SP',
    date: '2025-03-01',
    valid_until: '2025-03-20',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    status: 'Aprovado',
    items: [
      { id: 'item_1', description: 'Pintura de paredes e teto com tinta acrílica acetinada', quantity: 150, unit: 'm²', unit_price: 25.00, total_price: 3750.00 },
      { id: 'item_2', description: 'Aplicação de massa corrida e lixamento mecanizado', quantity: 150, unit: 'm²', unit_price: 22.00, total_price: 3300.00 },
      { id: 'item_3', description: 'Instalação de rodapé de poliestireno 10cm', quantity: 60, unit: 'm', unit_price: 30.00, total_price: 1800.00 },
      { id: 'item_4', description: 'Revisão e substituição de pontos de iluminação LED', quantity: 18, unit: 'un', unit_price: 45.00, total_price: 810.00 },
    ],
    client_materials: [
      { id: 'mat_1', description: 'Tinta Acrílica Fosca Lavável Suvinil/Coral (Lata 18L)', quantity: 2, unit: 'lata', estimated_price: 420.00, total_price: 840.00 },
      { id: 'mat_2', description: 'Massa Corrida PVA para Paredes Internas (Barrica 25kg)', quantity: 3, unit: 'barrica', estimated_price: 95.00, total_price: 285.00 },
      { id: 'mat_3', description: 'Selador Acrílico Branco Fosco (Galão 3.6L)', quantity: 2, unit: 'galão', estimated_price: 68.00, total_price: 136.00 },
      { id: 'mat_4', description: 'Fita Crepe Azul para Pintura 48mm x 50m', quantity: 4, unit: 'rolo', estimated_price: 18.50, total_price: 74.00 },
      { id: 'mat_5', description: 'Lixas para Parede Grão 150 e 220', quantity: 12, unit: 'un', estimated_price: 3.50, total_price: 42.00 },
      { id: 'mat_6', description: 'Lona Plástica para Proteção de Pisos e Móveis', quantity: 2, unit: 'rolo', estimated_price: 45.00, total_price: 90.00 },
    ],
    client_materials_total: 1467.00,
    client_expenses: [
      { id: 'exp_1', description: 'Caçamba Estacionária para Descarte de Resíduos e Entulho', quantity: 1, unit: 'un', unit_price: 380.00, total_price: 380.00 },
      { id: 'exp_2', description: 'Frete e Entrega dos Materiais Pesados na Obra', quantity: 1, unit: 'viagem', unit_price: 120.00, total_price: 120.00 },
    ],
    client_expenses_total: 500.00,
    subtotal: 9660.00,
    discount: 460.00,
    addition: 0,
    total: 9200.00,
    payment_terms: '40% na entrada + 30% na metade + 30% na entrega',
    execution_period: '15 dias úteis',
    notes: 'Inclui proteção completa de piso com papelão ondulado e fita crepe de alta fixação.',
    created_at: '2025-03-01',
  },
  {
    id: 'orc_002',
    code: 'ORC-2025-002',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_maria',
    client_name: 'Maria Santos Oliveira',
    client_phone: '(11) 98234-5678',
    client_address: 'Alameda dos Anapurus, 1240 - Indianópolis, São Paulo - SP',
    date: '2025-03-03',
    valid_until: '2025-03-23',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    status: 'Aguardando resposta',
    items: [
      { id: 'item_21', description: 'Lavagem em alta pressão e impermeabilização de fachada', quantity: 240, unit: 'm²', unit_price: 38.00, total_price: 9120.00 },
      { id: 'item_22', description: 'Pintura externa emborrachada resistente a intempéries', quantity: 240, unit: 'm²', unit_price: 42.00, total_price: 10080.00 },
      { id: 'item_23', description: 'Substituição e calafetação de calhas de zinco', quantity: 35, unit: 'm', unit_price: 65.00, total_price: 2275.00 },
    ],
    client_materials: [
      { id: 'mat_21', description: 'Tinta Emborrachada Fachada Total Impermeabilizante (Lata 18L)', quantity: 4, unit: 'lata', estimated_price: 490.00, total_price: 1960.00 },
      { id: 'mat_22', description: 'Fundo Preparador Base Água (Lata 18L)', quantity: 2, unit: 'lata', estimated_price: 340.00, total_price: 680.00 },
      { id: 'mat_23', description: 'Calhas de Zinco Corte 33 com Suportes e Emendas', quantity: 35, unit: 'm', estimated_price: 48.00, total_price: 1680.00 },
      { id: 'mat_24', description: 'Selante Poliuretano PU Construção 400g', quantity: 8, unit: 'tubo', estimated_price: 35.00, total_price: 280.00 },
    ],
    client_materials_total: 4600.00,
    client_expenses: [
      { id: 'exp_21', description: 'Aluguel de Andaime Fachadeiro com Guarda-Corpo (15 dias)', quantity: 1, unit: 'quinzena', unit_price: 850.00, total_price: 850.00 },
      { id: 'exp_22', description: 'Caçamba de Entulho para Remoção de Calhas Antigas', quantity: 1, unit: 'un', unit_price: 380.00, total_price: 380.00 },
    ],
    client_expenses_total: 1230.00,
    subtotal: 21475.00,
    discount: 1475.00,
    addition: 0,
    total: 20000.00,
    payment_terms: 'Entrada via PIX + 3 parcelas no cartão de crédito',
    execution_period: '20 dias corridos',
    notes: 'Garantia de 5 anos para o sistema de impermeabilização.',
    created_at: '2025-03-03',
  },
  {
    id: 'orc_003',
    code: 'ORC-2025-003',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_empresa_abc',
    client_name: 'Empresa ABC Empreendimentos',
    client_phone: '(11) 97345-6789',
    client_address: 'Av. Faria Lima, 3477 - Itaim Bibi, São Paulo - SP',
    date: '2025-03-04',
    valid_until: '2025-03-24',
    responsible_id: 'usr_marcos',
    responsible_name: 'Marcos Rezende',
    status: 'Enviado',
    items: [
      { id: 'item_31', description: 'Instalação de infraestrutura para rede e quadro elétrico trifásico', quantity: 1, unit: 'vb', unit_price: 8500.00, total_price: 8500.00 },
      { id: 'item_32', description: 'Montagem de perfilados e luminárias lineares pendentes', quantity: 45, unit: 'un', unit_price: 120.00, total_price: 5400.00 },
      { id: 'item_33', description: 'Emissão de ART de execução e laudo técnico', quantity: 1, unit: 'un', unit_price: 1250.00, total_price: 1250.00 },
    ],
    subtotal: 15150.00,
    discount: 0,
    addition: 0,
    total: 15150.00,
    payment_terms: 'Faturamento via Boleto 15/30/45 dias',
    execution_period: '12 dias úteis',
    notes: 'Serviço executado fora do horário comercial conforme exigência do condomínio.',
    created_at: '2025-03-04',
  },
  {
    id: 'orc_004',
    code: 'ORC-2025-004',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_joao_silva',
    client_name: 'João Silva Souza',
    client_phone: '(11) 96456-7890',
    client_address: 'Rua Bela Cintra, 740 - Consolação, São Paulo - SP',
    date: '2025-03-05',
    valid_until: '2025-03-25',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    status: 'Novo',
    items: [
      { id: 'item_41', description: 'Estruturação metálica de mezanino em vigas I', quantity: 40, unit: 'm²', unit_price: 180.00, total_price: 7200.00 },
      { id: 'item_42', description: 'Piso de painel wall e revestimento vinílico colado', quantity: 40, unit: 'm²', unit_price: 110.00, total_price: 4400.00 },
    ],
    subtotal: 11600.00,
    discount: 0,
    addition: 0,
    total: 11600.00,
    payment_terms: '50% entrada e 50% na conclusão',
    execution_period: '10 dias úteis',
    notes: 'Orçamento gerado recentemente após visita técnica.',
    created_at: '2025-03-05',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'app_001',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    phone: '(11) 99123-4567',
    whatsapp: '(11) 99123-4567',
    address: 'Rua das Palmeiras, 350 - Moema, SP',
    date: new Date().toISOString().split('T')[0], // Today
    time: '09:00',
    responsible_id: 'usr_joao',
    responsible_name: 'João Pedro',
    service_type: 'Visita técnica de reforma',
    value: 350.00,
    notes: 'Avaliar remoção de divisória de gesso e nivelamento de contrapiso.',
    status: 'Confirmado',
    created_at: '2025-03-01',
  },
  {
    id: 'app_002',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_maria',
    client_name: 'Maria Oliveira',
    phone: '(11) 98234-5678',
    whatsapp: '(11) 98234-5678',
    address: 'Alameda dos Anapurus, 1240 - Indianópolis, SP',
    date: new Date().toISOString().split('T')[0], // Today
    time: '11:30',
    responsible_id: 'usr_marcos',
    responsible_name: 'Marcos Rezende',
    service_type: 'Medição para orçamento de pintura',
    value: 280.00,
    notes: 'Levar catálogo de cores e trena a laser.',
    status: 'Agendado',
    created_at: '2025-03-02',
  },
  {
    id: 'app_003',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_empresa_abc',
    client_name: 'Empresa ABC',
    phone: '(11) 97345-6789',
    whatsapp: '(11) 97345-6789',
    address: 'Av. Faria Lima, 3477 - Itaim Bibi, SP',
    date: new Date().toISOString().split('T')[0], // Today
    time: '14:00',
    responsible_id: 'usr_fabio',
    responsible_name: 'Fábio Mendes',
    service_type: 'Início de obra / Reunião de alinhamento',
    value: 1200.00,
    notes: 'Entregar crachás da equipe na recepção do condomínio.',
    status: 'Em atendimento',
    created_at: '2025-03-03',
  },
  {
    id: 'app_004',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_joao_silva',
    client_name: 'João Silva Souza',
    phone: '(11) 96456-7890',
    whatsapp: '(11) 96456-7890',
    address: 'Rua Bela Cintra, 740 - Consolação, São Paulo - SP',
    date: new Date().toISOString().split('T')[0], // Today
    time: '14:30',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    service_type: 'Visita técnica de medição e orçamento de reforma',
    value: 450.00,
    notes: 'Avaliar remoção de revestimentos e projeto de gesso e elétrica.',
    status: 'Agendado',
    created_at: '2025-03-04',
  },
  {
    id: 'app_005',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    phone: '(11) 99123-4567',
    whatsapp: '(11) 99123-4567',
    address: 'Rua das Palmeiras, 350 - Moema, São Paulo - SP',
    date: new Date().toISOString().split('T')[0], // Today
    time: '10:00',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    service_type: 'Vistoria e orçamento de impermeabilização e pintura',
    value: 380.00,
    notes: 'Cliente já confirmou presença no local. Levar trena digital.',
    status: 'Confirmado',
    created_at: '2025-03-04',
  },
  {
    id: 'app_006',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_maria',
    client_name: 'Maria Santos Oliveira',
    phone: '(11) 98234-5678',
    whatsapp: '(11) 98234-5678',
    address: 'Alameda dos Anapurus, 1240 - Indianópolis, São Paulo - SP',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    time: '11:00',
    responsible_id: 'usr_larissa',
    responsible_name: 'Larissa Alencar',
    service_type: 'Visita técnica de acabamento fino e pisos',
    value: 500.00,
    notes: 'Apresentar amostras de materiais e definir metragem exata.',
    status: 'Agendado',
    created_at: '2025-03-05',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_001',
    code: 'OBR-2025-001',
    name: 'Reforma e Pintura de Apartamento',
    company_id: DEFAULT_COMPANY_ID,
    quote_id: 'orc_001',
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    phone: '(11) 99123-4567',
    client_phone: '(11) 99123-4567',
    whatsapp: '(11) 99123-4567',
    address: 'Rua das Palmeiras, 350 - Moema, São Paulo - SP',
    start_date: '2025-02-20',
    expected_completion_date: '2025-03-25',
    responsible_id: 'usr_marcos',
    responsible_name: 'Marcos Rezende',
    team_members: ['João Pedro Mestre', 'Lucas Pedreiro', 'Robson Pintor'],
    total_value: 20000.00,
    received_value: 12000.00,
    progress: 60,
    status: 'Em andamento',
    notes: 'Obra residencial em ritmo excelente. Cliente muito satisfeito com a proteção do piso.',
    daily_logs: [
      {
        id: 'log_1',
        project_id: 'prj_001',
        date: '2025-03-08',
        description: 'Finalizado o lixamento mecânico da sala e quartos. Iniciada a forração para pintura.',
        workers_present: ['João Pedro Mestre', 'Robson Pintor'],
      }
    ],
    tasks: [
      { id: 'tsk_1', project_id: 'prj_001', title: 'Proteção do ambiente e forração', responsible_name: 'João Pedro', due_date: '2025-02-21', status: 'Concluído', completed: true, notes: 'Papelão e lona aplicados' },
      { id: 'tsk_2', project_id: 'prj_001', title: 'Preparação e lixamento das paredes', responsible_name: 'Robson Pintor', due_date: '2025-02-26', status: 'Concluído', completed: true },
      { id: 'tsk_3', project_id: 'prj_001', title: 'Aplicação de massa corrida em 2 demãos', responsible_name: 'Robson Pintor', due_date: '2025-03-05', status: 'Concluído', completed: true },
      { id: 'tsk_4', project_id: 'prj_001', title: 'Lixamento fino mecanizado', responsible_name: 'Robson Pintor', due_date: '2025-03-10', status: 'Em execução', completed: false },
      { id: 'tsk_5', project_id: 'prj_001', title: 'Primeira demão de tinta acrílica acetinada', responsible_name: 'Robson Pintor', due_date: '2025-03-15', status: 'Pendente', completed: false },
      { id: 'tsk_6', project_id: 'prj_001', title: 'Segunda demão e retoques finos', responsible_name: 'Robson Pintor', due_date: '2025-03-20', status: 'Pendente', completed: false },
      { id: 'tsk_7', project_id: 'prj_001', title: 'Instalação de rodapés e espelhos elétricos', responsible_name: 'Lucas Pedreiro', due_date: '2025-03-22', status: 'Pendente', completed: false },
      { id: 'tsk_8', project_id: 'prj_001', title: 'Limpeza pós-obra detalhada e entrega', responsible_name: 'Equipe OZI', due_date: '2025-03-25', status: 'Pendente', completed: false },
    ],
    photos: [
      {
        id: 'pht_1',
        project_id: 'prj_001',
        stage: 'ANTES',
        category: 'Antes',
        url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
        caption: 'Estado inicial da sala antes da preparação',
        created_at: '2025-02-20',
      },
      {
        id: 'pht_2',
        project_id: 'prj_001',
        stage: 'DURANTE',
        category: 'Durante',
        url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&auto=format&fit=crop&q=80',
        caption: 'Aplicação de massa corrida e forração protetora',
        created_at: '2025-03-02',
      },
      {
        id: 'pht_3',
        project_id: 'prj_001',
        stage: 'DEPOIS',
        category: 'Depois',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
        caption: 'Ambiente finalizado com pintura perfeita e iluminação LED',
        created_at: '2025-03-10',
      },
    ],
    created_at: '2025-02-15',
  },
  {
    id: 'prj_002',
    code: 'OBR-2025-002',
    name: 'Infraestrutura Elétrica Comercial',
    company_id: DEFAULT_COMPANY_ID,
    quote_id: 'orc_003',
    client_id: 'cli_empresa_abc',
    client_name: 'Empresa ABC Empreendimentos',
    phone: '(11) 97345-6789',
    client_phone: '(11) 97345-6789',
    whatsapp: '(11) 97345-6789',
    address: 'Av. Faria Lima, 3477 - 9º Andar - Itaim Bibi, SP',
    start_date: '2025-03-10',
    expected_completion_date: '2025-03-28',
    responsible_id: 'usr_fabio',
    responsible_name: 'Fábio Mendes',
    team_members: ['João Pedro Mestre', 'Carlos Eletricista'],
    total_value: 15150.00,
    received_value: 5000.00,
    progress: 25,
    status: 'Em andamento',
    notes: 'Acesso liberado a partir das 19h com portaria noturna.',
    daily_logs: [],
    tasks: [
      { id: 'tsk_21', project_id: 'prj_002', title: 'Checagem de carga no QGBT', responsible_name: 'Carlos Eletricista', due_date: '2025-03-11', status: 'Concluído', completed: true },
      { id: 'tsk_22', project_id: 'prj_002', title: 'Passagem de cabos de 16mm²', responsible_name: 'Carlos Eletricista', due_date: '2025-03-16', status: 'Em execução', completed: false },
      { id: 'tsk_23', project_id: 'prj_002', title: 'Instalação das calhas e iluminação LED', responsible_name: 'João Pedro', due_date: '2025-03-24', status: 'Pendente', completed: false },
    ],
    photos: [],
    created_at: '2025-03-04',
  },
  {
    id: 'prj_003',
    code: 'OBR-2025-003',
    name: 'Mezanino e Reforma Estrutural',
    company_id: DEFAULT_COMPANY_ID,
    client_id: 'cli_joao_silva',
    client_name: 'João Silva Souza',
    phone: '(11) 96456-7890',
    client_phone: '(11) 96456-7890',
    whatsapp: '(11) 96456-7890',
    address: 'Rua Bela Cintra, 740 - Consolação, SP',
    start_date: '2025-01-10',
    expected_completion_date: '2025-02-15',
    actual_completion_date: '2025-02-14',
    responsible_id: 'usr_marcos',
    responsible_name: 'Marcos Rezende',
    team_members: ['Robson Pintor', 'Lucas Pedreiro'],
    total_value: 13200.00,
    received_value: 13200.00,
    progress: 100,
    status: 'Concluída',
    notes: 'Obra concluída antes do prazo. Termo de entrega assinado.',
    daily_logs: [],
    tasks: [
      { id: 'tsk_31', project_id: 'prj_003', title: 'Estruturação', status: 'Concluído', completed: true },
      { id: 'tsk_32', project_id: 'prj_003', title: 'Pintura geral', status: 'Concluído', completed: true },
      { id: 'tsk_33', project_id: 'prj_003', title: 'Limpeza e vistoria', status: 'Concluído', completed: true },
    ],
    photos: [],
    created_at: '2025-01-08',
  },
];

export const INITIAL_FINANCIAL_ENTRIES: FinancialEntry[] = [
  {
    id: 'ent_001',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    description: 'Entrada 50% - Reforma Moema',
    amount: 10000.00,
    date: '2025-02-20',
    payment_method: 'PIX',
    status: 'Recebido',
    created_at: '2025-02-20',
  },
  {
    id: 'ent_002',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    description: 'Segunda parcela (medição intermediária)',
    amount: 2000.00,
    date: '2025-03-02',
    payment_method: 'Transferência',
    status: 'Recebido',
    created_at: '2025-03-02',
  },
  {
    id: 'ent_003',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_002',
    project_title: 'OBR-2025-002 - Empresa ABC',
    client_id: 'cli_empresa_abc',
    client_name: 'Empresa ABC Empreendimentos',
    description: 'Sinal de contratação elétrica',
    amount: 5000.00,
    date: '2025-03-04',
    payment_method: 'Boleto',
    status: 'Recebido',
    created_at: '2025-03-04',
  },
  {
    id: 'ent_004',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_003',
    project_title: 'OBR-2025-003 - João Silva',
    client_id: 'cli_joao_silva',
    client_name: 'João Silva Souza',
    description: 'Quitação final obra mezanino',
    amount: 13200.00,
    date: '2025-02-14',
    payment_method: 'PIX',
    status: 'Recebido',
    created_at: '2025-02-14',
  },
  {
    id: 'ent_005',
    company_id: DEFAULT_COMPANY_ID,
    client_name: 'Condomínio Solar',
    description: 'Manutenção preventiva de bombas e pressurizadores',
    amount: 18150.00,
    date: '2025-03-01',
    payment_method: 'PIX',
    status: 'Recebido',
    created_at: '2025-03-01',
  },
  {
    id: 'ent_006',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    client_id: 'cli_carlos',
    client_name: 'Carlos Silva',
    description: 'Parcela final na entrega das chaves',
    amount: 8000.00,
    date: '2025-03-25',
    payment_method: 'PIX',
    status: 'Pendente',
    created_at: '2025-02-20',
  },
  {
    id: 'ent_007',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_002',
    project_title: 'OBR-2025-002 - Empresa ABC',
    client_id: 'cli_empresa_abc',
    client_name: 'Empresa ABC Empreendimentos',
    description: 'Segunda medição obra elétrica',
    amount: 10150.00,
    date: '2025-03-28',
    payment_method: 'Boleto',
    status: 'Pendente',
    created_at: '2025-03-04',
  },
];

export const INITIAL_FINANCIAL_EXPENSES: FinancialExpense[] = [
  {
    id: 'exp_001',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    category: 'Material',
    description: 'Tintas Suvinil acetinada + massa corrida 18L + lixas',
    amount: 3200.00,
    date: '2025-02-22',
    supplier: 'Leroy Merlin Morumbi',
    payment_method: 'Cartão',
    status: 'Pago',
    created_at: '2025-02-22',
  },
  {
    id: 'exp_002',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    category: 'Funcionários',
    description: 'Pagamento quinzenal pintor e ajudante',
    amount: 2500.00,
    date: '2025-03-05',
    supplier: 'Equipe de Pintura',
    payment_method: 'PIX',
    status: 'Pago',
    created_at: '2025-03-05',
  },
  {
    id: 'exp_003',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_001',
    project_title: 'OBR-2025-001 - Carlos Silva',
    category: 'Transporte',
    description: 'Frete e entrega de materiais pesados na obra',
    amount: 800.00,
    date: '2025-02-23',
    supplier: 'Transportadora Express',
    payment_method: 'PIX',
    status: 'Pago',
    created_at: '2025-02-23',
  },
  {
    id: 'exp_004',
    company_id: DEFAULT_COMPANY_ID,
    project_id: 'prj_002',
    project_title: 'OBR-2025-002 - Empresa ABC',
    category: 'Material',
    description: 'Cabos 16mm², disjuntores bipolares e perfilados',
    amount: 4850.00,
    date: '2025-03-05',
    supplier: 'Andra Materiais Elétricos',
    payment_method: 'Boleto',
    status: 'Pago',
    created_at: '2025-03-05',
  },
  {
    id: 'exp_005',
    company_id: DEFAULT_COMPANY_ID,
    category: 'Combustível',
    description: 'Abastecimento frota utilitários da semana',
    amount: 980.00,
    date: '2025-03-02',
    supplier: 'Posto Shell Bandeirantes',
    payment_method: 'Cartão',
    status: 'Pago',
    created_at: '2025-03-02',
  },
  {
    id: 'exp_006',
    company_id: DEFAULT_COMPANY_ID,
    category: 'Ferramentas',
    description: 'Manutenção lixadeira girafa e aspirador industrial',
    amount: 650.00,
    date: '2025-03-03',
    supplier: 'Makita Assistência Técnica',
    payment_method: 'PIX',
    status: 'Pago',
    created_at: '2025-03-03',
  },
  {
    id: 'exp_007',
    company_id: DEFAULT_COMPANY_ID,
    category: 'Alimentação',
    description: 'Café da manhã e almoço equipe de obras',
    amount: 1140.00,
    date: '2025-03-04',
    supplier: 'Restaurante Sabor Caseiro',
    payment_method: 'Cartão',
    status: 'Pago',
    created_at: '2025-03-04',
  },
  {
    id: 'exp_008',
    company_id: DEFAULT_COMPANY_ID,
    category: 'Impostos',
    description: 'DAS Simples Nacional competência',
    amount: 3300.00,
    date: '2025-03-20',
    supplier: 'Receita Federal',
    payment_method: 'Boleto',
    status: 'Pendente',
    created_at: '2025-03-01',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    title: 'Visita Técnica Agendada',
    description: 'Você possui orçamento com Carlos Silva às 09:00 hoje.',
    type: 'appointment',
    timestamp: 'Hoje, 08:30',
    read: false,
    action_tab: 'appointments',
  },
  {
    id: 'notif_2',
    title: 'Início de Obra Próximo',
    description: 'Obra na Empresa ABC inicia às 14:00. Equipe alocada.',
    type: 'project',
    timestamp: 'Hoje, 09:15',
    read: false,
    action_tab: 'projects',
  },
  {
    id: 'notif_3',
    title: 'Orçamento Aguardando Resposta',
    description: 'Orçamento ORC-2025-002 (Maria Santos) enviado há 4 dias.',
    type: 'quote',
    timestamp: 'Ontem',
    read: false,
    action_tab: 'quotes',
  },
  {
    id: 'notif_4',
    title: 'Contas a Pagar',
    description: 'Imposto DAS Simples Nacional vence em breve (R$ 3.300,00).',
    type: 'financial',
    timestamp: 'Ontem',
    read: true,
    action_tab: 'financial',
  },
];

export const DEFAULT_MONTHLY_GOAL: MonthlyGoal = {
  month: '2026-09',
  total_expenses: 15400.00, // Gastos do mês
  work_days: 22, // 22 dias úteis
  profit_goal: 0,
  daily_goal: 700.00, // 15400 / 22 = 700 por dia
  notes: 'Meta diluída por 22 dias úteis',
  expenses_breakdown: [
    { id: 'exp_1', description: 'Conta de Luz (Energia)', date: '2026-09-10', amount: 950.00, category: 'Utilidades' },
    { id: 'exp_2', description: 'Conta de Água e Saneamento', date: '2026-09-12', amount: 250.00, category: 'Utilidades' },
    { id: 'exp_3', description: 'Aluguel do Galpão / Escritório', date: '2026-09-05', amount: 4200.00, category: 'Estrutura' },
    { id: 'exp_4', description: 'Internet e Telefonia', date: '2026-09-08', amount: 380.00, category: 'Comunicação' },
    { id: 'exp_5', description: 'Combustível e Manutenção Veículos', date: '2026-09-15', amount: 2400.00, category: 'Transporte' },
    { id: 'exp_6', description: 'Equipe e Mão de Obra Fixa', date: '2026-09-20', amount: 6220.00, category: 'Pessoal' },
    { id: 'exp_7', description: 'Ferramentas e Consumíveis', date: '2026-09-18', amount: 1000.00, category: 'Operação' },
  ],
};

// Helper to get / set from localStorage with fallback to default
export function loadFromStorage<T>(key: string, fallback: T): T {
  try {
    const item = localStorage.getItem(`ozi_${key}`);
    if (!item) return fallback;
    return JSON.parse(item) as T;
  } catch (err) {
    console.error(`Error loading ${key} from storage:`, err);
    return fallback;
  }
}

export function saveToStorage<T>(key: string, value: T): void {
  try {
    localStorage.setItem(`ozi_${key}`, JSON.stringify(value));
  } catch (err) {
    console.error(`Error saving ${key} to storage:`, err);
  }
}

export function resetAllToDemoData(): void {
  localStorage.removeItem('ozi_company');
  localStorage.removeItem('ozi_users');
  localStorage.removeItem('ozi_clients');
  localStorage.removeItem('ozi_quotes');
  localStorage.removeItem('ozi_appointments');
  localStorage.removeItem('ozi_projects');
  localStorage.removeItem('ozi_entries');
  localStorage.removeItem('ozi_expenses');
  localStorage.removeItem('ozi_notifications');
  localStorage.removeItem('ozi_monthly_goals');
}
